Stockszilla/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('quotes/', include('quotes.urls')),
]

urlpatterns += [
    path('portfolio', include('portfolio.urls', namespace='portfolio')),
]
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

accounts/urls.py
from django.urls import path
from .import views
from .views import signup_view

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
]

portfolio/urls.py
from django.urls import path,include
from . import views

app_name="portfolio"
urlpatterns=[
path('buystocks<str:symbol>/',views.buy_stocks,name='buy_stocks'),
path('buy<str:symbol>/',views.buy,name='buy'),
path('buy<str:symbol>/<int:quantity>/',views.buy_share,name='buy_share'),
path('records/',views.transactions,name='transaction'),
path('transaction/<int:id>/',views.user_transaction,name='user_transaction'),
path('user_holdings/<str:symbol>/',views.user_holdings,name='user_holding'),
path('sell/<int:id>/',views.sell,name='sell'),
path('sell_stocks/<int:id>/',views.sell_stocks,name='sell_stocks'),
path('sell_share/<int:id>/<int:quantity>',views.sell_share,name='sell_share'),
path('holdings/',views.holdings,name='holding'),
path('leaderboard/',views.leaderboard,name='leaderboard'),
path('todays_report/',views.report,name='report'),
path('<str:symbol>/',views.cancel,name='cancel'),
]

urlpatterns+=[
path('quotes',include('quotes.urls')),
]

quotes/urls.py
from django.urls import path
from . import views


urlpatterns=[
path('',views.stocks,name='stocks'),
path('company/',views.company,name="company"),
path('company/<str:ticker>',views.graph,name="graph"),
path('<str:symbol>',views.company_stocks,name='company_stocks'),
path('Add_to_favourites/<str:symbol>',views.add_to_favourites,name='favourites'),
path('favourites/',views.fav,name='fav'),
]

templates/base_layout.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <style>
      footer a{ color: #ffffff;}
      footer a:hover{ color: #ffffff;}
    </style>
    <title>Stockszilla</title>
  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Stockszilla</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      {% if user.is_authenticated %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'stocks' %}">Company Stocks<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'fav' %}">Favourites<span class="sr-only">(current)</span></a>
      </li>
       <li class="nav-item active">
        <a class="nav-link" href="{% url 'portfolio:transaction' %}">Transactions</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'portfolio:holding' %}">Holdings</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'portfolio:report' %}">Today's Report</a>
      </li>
       <li class="nav-item active">
        <a class="nav-link" href="{% url 'portfolio:leaderboard' %}">Leaderboard</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'stocks' %}">
          <form class="logout-link" action="{% url 'accounts:logout' %}" method="POST">
              {% csrf_token %}
              <button class="float-right bg-dark text-white" type="submit" style="position: absolute; right: 0;">Logout</button>
            </form>
            <span class="sr-only">(current)</span></a>
      </li>
      {% else %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'accounts:login' %}">Login<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up<span class="sr-only">(current)</span></a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>

  <div class="container">
    {% block content %}
    {% endblock %}
  </div>

  <footer class="bg-dark text-white">
    <div class="container py-3">
        <div class="col-lg-6 col-sm-6 pb-2">
          <h4>Contact Us</h4>
          <p>
            <strong>Phone:</strong> +91-1000000000<br>
            <strong>Email:</strong><a href=""> stockszilla@gmail.com</a><br>
          </p>
        </div>
        <div class="text-center">Developed by Binary Buggers</div> 
    </div>
    <div class="container-fluid text-center bg-secondary py-2">
      &copy; 2020. All rights are reserved.
    </div>
  </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

templates/homepage.html
{% extends 'base_layout.html' %} {% block content %}
<h1 class="display-1 font-weight-bold text-responsive" style="color:#1C2833">STOCKSZILLA</h1>
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-block w-100" src="/media/pexels-david-mcbee-730564.jpg" width="50%" height="500px" alt="First slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="/media/pexels-energepiccom-159888.jpg" width="50%" height="500px" alt="Second slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="/media/pexels-lukas-669610.jpg" width="50%" height="500px" alt="Third slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="/media/pexels-timur-saglambilek-185576.jpg" height="500px" width="50%" alt="Third slide">
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  <br><br>
  <blockquote class="blockquote text-center">
    <p class="mb-0">Your one stop solution for stock market and place to build your stock portfolio even before investing!</p>
  </blockquote>
  <br>
<h1 class="font-weight-bold">About Us!</h1>
<blockquote class="blockquote text-justify">
    <p class="mb-0">Stockszilla is a Virtual Stock Market Website which uses accurate and real-time stock market data to paint the picture of investment portfolio for prospective investors. Interested traders can sign up on our website for free and practice trading using Virtual Money!
        You can search tickers for any stock and view its current and past performance visually. You can also buy and sell stocks using virtual money and build up your experience in this field! You can also build up a portfolio for yourself!</p>
  </blockquote>
  <br><br><br><br><br>
{% endblock %}